# 공통 개발 환경
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop # 추후 변경
    show-sql: true
    properties:
      hibernate:
        format_sql: false
