server:
  port: 8080
  servlet:
    session:
      context-path: /
      encoding:
        charset: UTF-8
        force-response: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
        orm:
          jpa: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"