server:
  port: 8080
  servlet:
    session:
      context-path: /
      encoding:
        charset: UTF-8
        enabled: true
        force: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
        orm:
          jpa: INFO